<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoices - Page {{ $page_number }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', 'Arial', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
        }
        .company-info {
            text-align: center;
            margin-bottom: 20px;
            font-size: 10px;
            color: #666;
        }
        .filter-info {
            background-color: #f5f5f5;
            padding: 10px;
            margin-bottom: 20px;
            font-size: 10px;
            border-radius: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .status-paid {
            color: green;
            font-weight: bold;
        }
        .status-pending {
            color: orange;
            font-weight: bold;
        }
        .status-overdue {
            color: red;
            font-weight: bold;
        }
        .footer {
            text-align: center;
            font-size: 10px;
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            color: #666;
        }
        .page-break {
            page-break-after: always;
        }
        .summary {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f9f9f9;
            border-left: 3px solid #333;
        }
        .summary p {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $companyInfo['name'] }}</h1>
        <p>Community Development Invoices - Page {{ $page_number }} of {{ $total_pages }}</p>
        <p>Generated: {{ $export_date }}</p>
        <p>Generated By: {{ $exported_by }}</p>
    </div>
    
    <div class="company-info">
        @if($companyInfo['email'])
            <p>Email: {{ $companyInfo['email'] }}</p>
        @endif
        @if($companyInfo['phone'])
            <p>Phone: {{ $companyInfo['phone'] }}</p>
        @endif
        @if($companyInfo['address'])
            <p>Address: {{ $companyInfo['address'] }}</p>
        @endif
    </div>
    
    @if(!empty($filters) && count(array_filter($filters)) > 0)
    <div class="filter-info">
        <strong>Applied Filters:</strong>
        @if(isset($filters['tenant_id']) && $filters['tenant_id'])
            <span>Tenant ID: {{ $filters['tenant_id'] }} | </span>
        @endif
        @if(isset($filters['property_unit_id']) && $filters['property_unit_id'])
            <span>Unit ID: {{ $filters['property_unit_id'] }} | </span>
        @endif
        @if(isset($filters['status']) && $filters['status'])
            <span>Status: {{ ucfirst($filters['status']) }} | </span>
        @endif
        @if(isset($filters['period']) && $filters['period'])
            <span>Period: {{ $filters['period'] }}</span>
        @endif
    </div>
    @endif
    
    <div class="summary">
        <strong>Summary:</strong>
        <p>Total Invoices on this page: {{ $invoices->count() }} | Total Invoices Overall: {{ $total_invoices }}</p>
        <p>Total Amount: {{ $settings->formatAmount($invoices->sum('total_amount')) }}</p>
        <p>Total Paid: {{ $settings->formatAmount($invoices->sum('paid_amount')) }}</p>
        <p>Total Balance: {{ $settings->formatAmount($invoices->sum('balance')) }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Tenant</th>
                <th>Property / Unit</th>
                <th>Period</th>
                <th>Due Date</th>
                <th>Total Amount</th>
                <th>Paid Amount</th>
                <th>Balance</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoices as $invoice)
            <tr>
                <td>{{ $invoice->invoice_number }}</td>
                <td>
                    {{ $invoice->tenant->name ?? 'Unknown' }}<br>
                    <small>{{ $invoice->tenant->email ?? '' }}</small>
                </td>
                <td>
                    {{ $invoice->propertyUnit->property->property_name ?? 'N/A' }}<br>
                    Unit: {{ $invoice->propertyUnit->unit_number ?? 'N/A' }}
                </td>
                <td>{{ \Carbon\Carbon::parse($invoice->period . '-01')->format('M Y') }}</td>
                <td>{{ $invoice->due_date->format('M d, Y') }}</td>
                <td>{{ $settings->formatAmount($invoice->total_amount) }}</td>
                <td>{{ $settings->formatAmount($invoice->paid_amount ?? 0) }}</td>
                <td>{{ $settings->formatAmount($invoice->balance) }}</td>
                <td class="status-{{ $invoice->status }}">
                    {{ ucfirst($invoice->status) }}
                    @if($invoice->penalty_amount > 0)
                        <br><small>Penalty: {{ $settings->formatAmount($invoice->penalty_amount) }}</small>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>This is a computer-generated document. No signature is required.</p>
        <p>Page {{ $page_number }} of {{ $total_pages }}</p>
    </div>
</body>
</html>