<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', 'Arial', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 20px;
        }
        .invoice-header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .invoice-header h1 {
            margin: 0;
            font-size: 28px;
            color: #333;
        }
        .invoice-header p {
            margin: 5px 0 0;
            color: #666;
        }
        .company-info {
            text-align: center;
            margin-bottom: 20px;
            font-size: 11px;
            color: #666;
        }
        .invoice-info {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
        }
        .invoice-info table {
            width: 100%;
            border-collapse: collapse;
        }
        .invoice-info td {
            padding: 5px;
        }
        .invoice-details {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .invoice-details th, .invoice-details td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .invoice-details th {
            background-color: #f2f2f2;
        }
        .totals {
            width: 300px;
            margin-left: auto;
            margin-bottom: 20px;
        }
        .totals table {
            width: 100%;
            border-collapse: collapse;
        }
        .totals td {
            padding: 5px;
            border: 1px solid #ddd;
        }
        .status-paid {
            color: green;
            font-weight: bold;
        }
        .status-pending {
            color: orange;
            font-weight: bold;
        }
        .status-overdue {
            color: red;
            font-weight: bold;
        }
        .footer {
            text-align: center;
            font-size: 10px;
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            color: #666;
        }
        .payment-info {
            margin-top: 20px;
            padding: 10px;
            background-color: #f0f0f0;
            border-left: 3px solid #4CAF50;
        }
        .warning {
            color: red;
            font-size: 11px;
        }
    </style>
</head>
<body>
    <div class="invoice-header">
        <h1>{{ $companyInfo['name'] }}</h1>
        <p>TAX INVOICE</p>
        <p>Invoice #: {{ $invoice->invoice_number }}</p>
    </div>
    
    <div class="company-info">
        @if($companyInfo['email']) Email: {{ $companyInfo['email'] }} @endif
        @if($companyInfo['phone']) | Phone: {{ $companyInfo['phone'] }} @endif
        @if($companyInfo['address']) | Address: {{ $companyInfo['address'] }} @endif
        @if($companyInfo['tax_id']) | TIN: {{ $companyInfo['tax_id'] }} @endif
    </div>
    
    <div class="invoice-info">
        <table>
            <tr>
                <td width="50%"><strong>Bill To:</strong></td>
                <td width="50%"><strong>Property Details:</strong></td>
            </tr>
            <tr>
                <td>
                    {{ $invoice->tenant->name ?? 'Unknown' }}<br>
                    {{ $invoice->tenant->email ?? '' }}<br>
                    {{ $invoice->tenant->phone ?? '' }}
                </td>
                <td>
                    {{ $invoice->propertyUnit->property->property_name ?? 'N/A' }}<br>
                    Unit Number: {{ $invoice->propertyUnit->unit_number ?? 'N/A' }}<br>
                    @if($invoice->propertyUnit->property->zone)
                        Zone: {{ $invoice->propertyUnit->property->zone }}
                    @endif
                </td>
            </tr>
        </table>
    </div>
    
    <table class="invoice-details">
        <tr>
            <th>Period</th>
            <th>Due Date</th>
            <th>Status</th>
            <th>Generated By</th>
            <th>Generated At</th>
        </tr>
        <tr>
            <td>{{ \Carbon\Carbon::parse($invoice->period . '-01')->format('F Y') }}</td>
            <td>{{ $invoice->due_date->format('F d, Y') }}</td>
            <td class="status-{{ $invoice->status }}">{{ ucfirst($invoice->status) }}</td>
            <td>{{ $generated_by }}</td>
            <td>{{ $generated_at }}</td>
        </tr>
    </table>
    
    <table class="invoice-details">
        <thead>
            <tr>
                <th>Description</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Community Development Dues ({{ \Carbon\Carbon::parse($invoice->period . '-01')->format('M Y') }})</td>
                <td>{{ $settings->formatAmount($invoice->community_dues) }}</td>
            </tr>
            @if($invoice->additional_charges > 0)
            <tr>
                <td>Additional Charges</td>
                <td>{{ $settings->formatAmount($invoice->additional_charges) }}</td>
            </tr>
            @endif
            @if($invoice->penalty_amount > 0)
            <tr>
                <td>Late Payment Penalty</td>
                <td>{{ $settings->formatAmount($invoice->penalty_amount) }}</td>
            </tr>
            @endif
        </tbody>
    </table>
    
    <div class="totals">
        <table>
            <tr>
                <td><strong>Subtotal:</strong></td>
                <td>{{ $settings->formatAmount($invoice->community_dues + $invoice->additional_charges) }}</td>
            </tr>
            @if($invoice->penalty_amount > 0)
            <tr>
                <td><strong>Penalty:</strong></td>
                <td>{{ $settings->formatAmount($invoice->penalty_amount) }}</td>
            </tr>
            @endif
            <tr style="background-color: #f2f2f2;">
                <td><strong>TOTAL:</strong></td>
                <td><strong>{{ $settings->formatAmount($invoice->total_amount) }}</strong></td>
            </tr>
            @if($invoice->paid_amount > 0)
            <tr>
                <td><strong>Amount Paid:</strong></td>
                <td>{{ $settings->formatAmount($invoice->paid_amount) }}</td>
            </tr>
            <tr>
                <td><strong>Balance Due:</strong></td>
                <td>{{ $settings->formatAmount($invoice->balance) }}</td>
            </tr>
            @endif
        </table>
    </div>
    
    @if($invoice->payment_method && $invoice->payment_date)
    <div class="payment-info">
        <strong>Payment Information:</strong><br>
        Method: {{ ucfirst(str_replace('_', ' ', $invoice->payment_method)) }}<br>
        Reference: {{ $invoice->payment_reference ?? 'N/A' }}<br>
        Date: {{ \Carbon\Carbon::parse($invoice->payment_date)->format('F d, Y') }}
    </div>
    @endif
    
    @if($paymentDetails['days_until_due'] < 0 && $invoice->status != 'paid')
    <div class="warning">
        <strong>⚠️ OVERDUE NOTICE:</strong> This invoice is {{ abs($paymentDetails['days_until_due']) }} days overdue. 
        Late payment penalties may apply as per system settings.
    </div>
    @endif
    
    <div class="footer">
        <p>This is a computer-generated invoice. No signature is required.</p>
        <p>Thank you for your prompt payment.</p>
    </div>
</body>
</html>