<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>All Invoices - {{ $export_date }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', 'Arial', sans-serif;
            font-size: 11px;
            line-height: 1.4;
            margin: 15px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 22px;
            color: #333;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
        }
        .company-info {
            text-align: center;
            margin-bottom: 15px;
            font-size: 10px;
            color: #666;
        }
        .filter-info {
            background-color: #f5f5f5;
            padding: 8px;
            margin-bottom: 15px;
            font-size: 9px;
            border-radius: 5px;
        }
        .summary-stats {
            background-color: #e8f4f8;
            padding: 10px;
            margin-bottom: 20px;
            border-left: 4px solid #2196F3;
        }
        .summary-stats h3 {
            margin: 0 0 8px 0;
            font-size: 14px;
        }
        .summary-stats p {
            margin: 3px 0;
            font-size: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            font-size: 9px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
            font-size: 10px;
        }
        .status-paid {
            color: green;
            font-weight: bold;
        }
        .status-pending {
            color: orange;
            font-weight: bold;
        }
        .status-overdue {
            color: red;
            font-weight: bold;
        }
        .footer {
            text-align: center;
            font-size: 9px;
            margin-top: 20px;
            padding-top: 8px;
            border-top: 1px solid #ddd;
            color: #666;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $companyInfo['name'] }}</h1>
        <p>Complete Invoice Report - All Filtered Invoices</p>
        <p>Generated: {{ $export_date }} | Generated By: {{ $exported_by }}</p>
    </div>
    
    <div class="company-info">
        @if($companyInfo['email']) {{ $companyInfo['email'] }} @endif
        @if($companyInfo['phone']) | Phone: {{ $companyInfo['phone'] }} @endif
        @if($companyInfo['address']) | {{ $companyInfo['address'] }} @endif
    </div>
    
    @if(!empty($filters) && count(array_filter($filters)) > 0)
    <div class="filter-info">
        <strong>Applied Filters:</strong>
        @if(isset($filters['tenant_id']) && $filters['tenant_id'])
            Tenant ID: {{ $filters['tenant_id'] }} | 
        @endif
        @if(isset($filters['property_unit_id']) && $filters['property_unit_id'])
            Unit ID: {{ $filters['property_unit_id'] }} | 
        @endif
        @if(isset($filters['status']) && $filters['status'])
            Status: {{ ucfirst($filters['status']) }} | 
        @endif
        @if(isset($filters['period']) && $filters['period'])
            Period: {{ $filters['period'] }}
        @endif
    </div>
    @endif
    
    <div class="summary-stats">
        <h3>Executive Summary</h3>
        <p><strong>Total Invoices:</strong> {{ $summary['total_invoices'] }}</p>
        <p><strong>Total Amount:</strong> {{ $settings->formatAmount($summary['total_amount']) }}</p>
        <p><strong>Total Paid:</strong> {{ $settings->formatAmount($summary['total_paid']) }}</p>
        <p><strong>Total Balance:</strong> {{ $settings->formatAmount($summary['total_balance']) }}</p>
        <p><strong>Total Penalties:</strong> {{ $settings->formatAmount($summary['total_penalties']) }}</p>
        <p><strong>Status Breakdown:</strong> Paid: {{ $summary['paid_invoices'] }} | Pending: {{ $summary['pending_invoices'] }} | Overdue: {{ $summary['overdue_invoices'] }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Tenant</th>
                <th>Property / Unit</th>
                <th>Period</th>
                <th>Due Date</th>
                <th>CD Amount</th>
                <th>Penalty</th>
                <th>Total</th>
                <th>Paid</th>
                <th>Balance</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoices as $invoice)
            <tr>
                <td>{{ $invoice->invoice_number }}</td>
                <td>
                    {{ $invoice->tenant->name ?? 'Unknown' }}
                    @if($invoice->tenant->phone)
                        <br><small>{{ $invoice->tenant->phone }}</small>
                    @endif
                </td>
                <td>
                    {{ $invoice->propertyUnit->property->property_name ?? 'N/A' }}<br>
                    Unit: {{ $invoice->propertyUnit->unit_number ?? 'N/A' }}
                </td>
                <td>{{ \Carbon\Carbon::parse($invoice->period . '-01')->format('M Y') }}</td>
                <td>{{ $invoice->due_date->format('M d, Y') }}</td>
                <td>{{ $settings->formatAmount($invoice->community_dues) }}</td>
                <td>{{ $settings->formatAmount($invoice->penalty_amount ?? 0) }}</td>
                <td>{{ $settings->formatAmount($invoice->total_amount) }}</td>
                <td>{{ $settings->formatAmount($invoice->paid_amount ?? 0) }}</td>
                <td>{{ $settings->formatAmount($invoice->balance) }}</td>
                <td class="status-{{ $invoice->status }}">
                    {{ ucfirst($invoice->status) }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>This report includes {{ $summary['total_invoices'] }} invoice(s) totaling {{ $settings->formatAmount($summary['total_amount']) }}</p>
        <p>Generated by {{ $exported_by }} on {{ $export_date }}</p>
    </div>
</body>
</html>