@extends('layouts.app')

@section('title', $qrCode->name . ' - QR Code Details')

@section('content')
<div class="grid grid-cols-1 gap-6 mb-6">
    <!-- Header Card -->
    <div class="card">
        <div class="p-6">
            <div class="flex justify-between items-start">
                <div class="flex items-center">
                    <div class="w-16 h-16 rounded-full flex items-center justify-center mr-4"
                         style="background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);">
                        <i class="fas fa-qrcode text-white text-xl"></i>
                    </div>
                    <div>
                        <h2 class="text-xl font-semibold flex items-center" style="color: var(--text-primary);">
                            <i class="fas fa-qrcode mr-2" style="color: var(--primary);"></i>
                            {{ $qrCode->name }}
                        </h2>
                        <div class="flex items-center mt-1 space-x-3 text-sm" style="color: var(--text-secondary);">
                            <span><i class="fas fa-map-marker-alt mr-1" style="color: var(--info);"></i> {{ $post->name }} ({{ $post->code }})</span>
                            <span>•</span>
                            <span><i class="fas fa-user-shield mr-1" style="color: var(--success);"></i> Generated by: {{ $qrCode->creator->name ?? 'System' }}</span>
                            @if($post->latitude && $post->longitude)
                                <span>•</span>
                                <span><i class="fas fa-satellite-dish mr-1" style="color: var(--warning);"></i> GPS Enabled</span>
                            @endif
                        </div>
                    </div>
                </div>
                
                <!-- Back to List Button Only -->
                <div class="flex items-center space-x-2">
                    <a href="{{ route('admin.security-posts.qr-codes.index', $post->id) }}" 
                       class="px-4 py-2 rounded-lg font-medium inline-flex items-center transition-all duration-200 hover:scale-105"
                       style="background-color: rgba(var(--secondary-rgb), 0.1); color: var(--secondary); border: 1px solid rgba(var(--secondary-rgb), 0.3);">
                        <i class="fas fa-arrow-left mr-2"></i> Back to List
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Breadcrumb Navigation (preserved) -->
    <div class="card p-4">
        <div class="flex items-center justify-between">
            <div class="flex items-center space-x-3">
                <a href="{{ route('admin.security-posts.index') }}" 
                   class="inline-flex items-center text-sm font-medium hover:underline"
                   style="color: var(--primary);">
                    <i class="fas fa-arrow-left mr-2"></i> Security Posts
                </a>
                <span style="color: var(--text-secondary);">/</span>
                <a href="{{ route('admin.security-posts.show', $post->id) }}" 
                   class="inline-flex items-center text-sm font-medium hover:underline"
                   style="color: var(--primary);">
                    {{ $post->name }}
                </a>
                <span style="color: var(--text-secondary);">/</span>
                <a href="{{ route('admin.security-posts.qr-codes.index', $post->id) }}" 
                   class="inline-flex items-center text-sm font-medium hover:underline"
                   style="color: var(--primary);">
                    QR Codes
                </a>
                <span style="color: var(--text-secondary);">/</span>
                <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium"
                      style="background-color: rgba(var(--info-rgb), 0.1); color: var(--info); border: 1px solid rgba(var(--info-rgb), 0.3);">
                    <i class="fas fa-info-circle mr-1"></i> Details
                </span>
            </div>
            <div class="text-sm" style="color: var(--text-secondary);">
                <i class="fas fa-calendar-alt mr-1" style="color: var(--info);"></i>
                {{ now()->format('l, F j, Y') }}
            </div>
        </div>
    </div>

    <!-- INSTRUCTIONS FOR SECURITY PERSONNEL - PROMINENT CARD (preserved) -->
    <div class="card overflow-hidden" style="border-left: 4px solid var(--primary);">
        <div class="p-6">
            <div class="flex items-start">
                <div class="flex-shrink-0 mr-4">
                    <div class="w-16 h-16 rounded-full flex items-center justify-center"
                         style="background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);">
                        <i class="fas fa-shield-alt text-white text-2xl"></i>
                    </div>
                </div>
                <div class="flex-1">
                    <h3 class="text-xl font-bold mb-3 flex items-center" style="color: var(--primary);">
                        <i class="fas fa-bullhorn mr-2"></i>
                        INSTRUCTIONS FOR SECURITY PERSONNEL
                    </h3>
                    
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <!-- Check-in Instructions -->
                        <div class="p-4 rounded-lg" style="background-color: rgba(var(--success-rgb), 0.05); border: 1px solid rgba(var(--success-rgb), 0.2);">
                            <h4 class="text-lg font-semibold mb-3 flex items-center" style="color: var(--success);">
                                <i class="fas fa-sign-in-alt mr-2"></i>
                                CHECK-IN PROCEDURE
                            </h4>
                            <ol class="list-decimal list-inside space-y-2" style="color: var(--text-primary);">
                                <li class="flex items-start">
                                    <span class="w-6 h-6 rounded-full flex items-center justify-center mr-2 flex-shrink-0" 
                                          style="background-color: var(--success); color: white; font-size: 12px;">1</span>
                                    <span>Open the attendance scanning app on your mobile device</span>
                                </li>
                                <li class="flex items-start">
                                    <span class="w-6 h-6 rounded-full flex items-center justify-center mr-2 flex-shrink-0" 
                                          style="background-color: var(--success); color: white; font-size: 12px;">2</span>
                                    <span>Select <strong>"Check-In"</strong> mode from the main menu</span>
                                </li>
                                <li class="flex items-start">
                                    <span class="w-6 h-6 rounded-full flex items-center justify-center mr-2 flex-shrink-0" 
                                          style="background-color: var(--success); color: white; font-size: 12px;">3</span>
                                    <span>Scan this QR code when personnel arrive at {{ $post->name }}</span>
                                </li>
                                <li class="flex items-start">
                                    <span class="w-6 h-6 rounded-full flex items-center justify-center mr-2 flex-shrink-0" 
                                          style="background-color: var(--success); color: white; font-size: 12px;">4</span>
                                    <span>Verify that the scanner shows <span style="color: var(--success);">"Check-In Successful"</span></span>
                                </li>
                                <li class="flex items-start">
                                    <span class="w-6 h-6 rounded-full flex items-center justify-center mr-2 flex-shrink-0" 
                                          style="background-color: var(--success); color: white; font-size: 12px;">5</span>
                                    <span>Confirm personnel details appear correctly on screen</span>
                                </li>
                            </ol>
                        </div>

                        <!-- Check-out Instructions -->
                        <div class="p-4 rounded-lg" style="background-color: rgba(var(--warning-rgb), 0.05); border: 1px solid rgba(var(--warning-rgb), 0.2);">
                            <h4 class="text-lg font-semibold mb-3 flex items-center" style="color: var(--warning);">
                                <i class="fas fa-sign-out-alt mr-2"></i>
                                CHECK-OUT PROCEDURE
                            </h4>
                            <ol class="list-decimal list-inside space-y-2" style="color: var(--text-primary);">
                                <li class="flex items-start">
                                    <span class="w-6 h-6 rounded-full flex items-center justify-center mr-2 flex-shrink-0" 
                                          style="background-color: var(--warning); color: white; font-size: 12px;">1</span>
                                    <span>Switch app to <strong>"Check-Out"</strong> mode</span>
                                </li>
                                <li class="flex items-start">
                                    <span class="w-6 h-6 rounded-full flex items-center justify-center mr-2 flex-shrink-0" 
                                          style="background-color: var(--warning); color: white; font-size: 12px;">2</span>
                                    <span>Scan the same QR code when personnel are leaving</span>
                                </li>
                                <li class="flex items-start">
                                    <span class="w-6 h-6 rounded-full flex items-center justify-center mr-2 flex-shrink-0" 
                                          style="background-color: var(--warning); color: white; font-size: 12px;">3</span>
                                    <span>Verify that the scanner shows <span style="color: var(--warning);">"Check-Out Successful"</span></span>
                                </li>
                                <li class="flex items-start">
                                    <span class="w-6 h-6 rounded-full flex items-center justify-center mr-2 flex-shrink-0" 
                                          style="background-color: var(--warning); color: white; font-size: 12px;">4</span>
                                    <span>Confirm total hours worked are displayed correctly</span>
                                </li>
                            </ol>
                        </div>
                    </div>

                    <!-- Important Notes for Security -->
                    <div class="mt-4 p-4 rounded-lg" style="background-color: rgba(var(--info-rgb), 0.05); border: 1px dashed var(--info);">
                        <div class="flex items-start">
                            <i class="fas fa-info-circle text-xl mr-3 mt-0.5" style="color: var(--info);"></i>
                            <div>
                                <h5 class="font-semibold mb-2" style="color: var(--info);">⚠️ IMPORTANT NOTES:</h5>
                                <ul class="space-y-1 text-sm" style="color: var(--text-primary);">
                                    <li><i class="fas fa-check-circle mr-2" style="color: var(--success);"></i> Always scan at the designated attendance point at {{ $post->name }}</li>
                                    <li><i class="fas fa-check-circle mr-2" style="color: var(--success);"></i> Ensure good lighting for successful scanning</li>
                                    <li><i class="fas fa-check-circle mr-2" style="color: var(--success);"></i> Do not share this QR code with unauthorized personnel</li>
                                    <li><i class="fas fa-check-circle mr-2" style="color: var(--success);"></i> Contact supervisor immediately if scanner shows errors</li>
                                    <li><i class="fas fa-check-circle mr-2" style="color: var(--success);"></i> This QR code is specifically for <strong>{{ $post->name }}</strong> only</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <!-- Quick Reference -->
                    <div class="mt-4 grid grid-cols-2 md:grid-cols-4 gap-3">
                        <div class="p-2 rounded text-center" style="background-color: var(--bg-secondary);">
                            <span class="text-xs" style="color: var(--text-secondary);">Post:</span>
                            <div class="font-bold text-sm" style="color: var(--primary);">{{ $post->code }}</div>
                        </div>
                        <div class="p-2 rounded text-center" style="background-color: var(--bg-secondary);">
                            <span class="text-xs" style="color: var(--text-secondary);">QR Type:</span>
                            <div class="font-bold text-sm" style="color: var(--primary);">{{ ucfirst(str_replace('_', ' ', $qrCode->code_type)) }}</div>
                        </div>
                        <div class="p-2 rounded text-center" style="background-color: var(--bg-secondary);">
                            <span class="text-xs" style="color: var(--text-secondary);">Valid Until:</span>
                            <div class="font-bold text-sm" style="color: var(--primary);">
                                @if($qrCode->code_type === 'static' && $qrCode->expires_at === null)
                                    <span>Permanent</span>
                                @elseif($qrCode->expires_at)
                                    {{ \Carbon\Carbon::parse($qrCode->expires_at)->format('d/m/Y') }}
                                @else
                                    N/A
                                @endif
                            </div>
                        </div>
                        <div class="p-2 rounded text-center" style="background-color: var(--bg-secondary);">
                            <span class="text-xs" style="color: var(--text-secondary);">GPS Required:</span>
                            <div class="font-bold text-sm" style="color: var(--primary);">{{ $post->latitude && $post->longitude ? 'Yes' : 'No' }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Main Content Grid (QR Code Image Card - preserved) -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- QR Code Image Card -->
        <div class="lg:col-span-1">
            <div class="card h-full">
                <div class="p-6 border-b" style="border-color: var(--border-color);">
                    <h3 class="text-lg font-semibold flex items-center" style="color: var(--text-primary);">
                        <i class="fas fa-qrcode mr-2" style="color: var(--primary);"></i>
                        Attendance QR Code
                    </h3>
                </div>
                <div class="p-6">
                    <div class="border-2 rounded-xl p-6 text-center transition-all duration-300 hover:shadow-lg" 
                         style="border-color: var(--border-color); background-color: var(--bg-secondary);">
                        @if($qrCode->image_path)
                            <div class="relative inline-block group">
                                <img src="{{ asset('storage/' . $qrCode->image_path) }}" 
                                     alt="{{ $qrCode->name }}" 
                                     class="mx-auto max-w-full h-auto rounded-lg transition-transform duration-300 group-hover:scale-105"
                                     style="max-width: 250px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
                                <div class="absolute inset-0 bg-black bg-opacity-0 group-hover:bg-opacity-10 transition-all duration-300 rounded-lg"></div>
                                
                                <!-- Printable Instructions Badge -->
                                <div class="absolute -top-2 -right-2 px-2 py-1 rounded-full text-xs font-bold"
                                     style="background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%); color: white;">
                                    <i class="fas fa-print mr-1"></i> POST THIS QR CODE
                                </div>
                            </div>
                            
                            <!-- Printable Instructions -->
                            <div class="mt-4 p-3 rounded-lg text-left"
                                 style="background-color: rgba(var(--primary-rgb), 0.05); border: 1px solid rgba(var(--primary-rgb), 0.2);">
                                <h4 class="text-xs font-bold uppercase mb-2" style="color: var(--primary);">
                                    <i class="fas fa-print mr-1"></i> For Printing & Posting:
                                </h4>
                                <p class="text-xs" style="color: var(--text-secondary);">
                                    1. Download and print this QR code<br>
                                    2. Laminate for durability<br>
                                    3. Post at the main entrance of {{ $post->name }}<br>
                                    4. Ensure it's at eye level for easy scanning
                                </p>
                            </div>
                        @else
                            <div class="w-48 h-48 mx-auto border-2 rounded-lg flex items-center justify-center animate-pulse"
                                 style="background: linear-gradient(135deg, rgba(var(--primary-rgb), 0.1), rgba(var(--secondary-rgb), 0.1)); border-color: var(--border-color);">
                                <i class="fas fa-qrcode text-6xl" style="color: var(--primary); opacity: 0.5;"></i>
                            </div>
                        @endif
                        
                        <div class="mt-6 space-y-3">
                            <div class="relative group">
                                <div class="text-sm font-mono p-3 rounded-lg break-all"
                                     style="background-color: rgba(var(--primary-rgb), 0.05); color: var(--text-primary); border: 1px solid rgba(var(--primary-rgb), 0.2);">
                                    {{ $qrCode->code }}
                                </div>
                                <button onclick="copyToClipboard('{{ $qrCode->code }}')" 
                                        class="absolute -top-2 -right-2 w-8 h-8 rounded-full flex items-center justify-center transition-all duration-200 hover:scale-110 copy-btn"
                                        style="background-color: var(--primary); color: white; box-shadow: 0 2px 4px rgba(0,0,0,0.2);"
                                        title="Copy Code">
                                    <i class="fas fa-copy text-sm"></i>
                                </button>
                            </div>

                            <div class="flex justify-center space-x-3 pt-4">
                                <button onclick="copyToClipboard('{{ $qrCode->code }}')" 
                                        class="action-btn w-10 h-10 rounded-lg transition-all duration-200 hover:scale-110 hover:shadow-lg"
                                        style="background-color: rgba(var(--info-rgb), 0.1); color: var(--info);"
                                        title="Copy Code">
                                    <i class="fas fa-copy"></i>
                                </button>
                                <a href="{{ route('admin.security-posts.qr-codes.download', [$post->id, $qrCode->id]) }}" 
                                   class="action-btn w-10 h-10 rounded-lg transition-all duration-200 hover:scale-110 hover:shadow-lg"
                                   style="background-color: rgba(var(--success-rgb), 0.1); color: var(--success);"
                                   title="Download QR Code for Printing">
                                    <i class="fas fa-download"></i>
                                </a>
                                <button onclick="window.print()"
                                        class="action-btn w-10 h-10 rounded-lg transition-all duration-200 hover:scale-110 hover:shadow-lg"
                                        style="background-color: rgba(var(--primary-rgb), 0.1); color: var(--primary);"
                                        title="Print QR Code">
                                    <i class="fas fa-print"></i>
                                </button>
                                <button onclick="showRegenerateModal({{ $qrCode->id }}, '{{ $qrCode->name }}')"
                                        class="action-btn w-10 h-10 rounded-lg transition-all duration-200 hover:scale-110 hover:shadow-lg"
                                        style="background-color: rgba(var(--warning-rgb), 0.1); color: var(--warning);"
                                        title="Regenerate QR Code">
                                    <i class="fas fa-sync-alt"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- QR Code Information Card (preserved) -->
        <div class="lg:col-span-2">
            <div class="card h-full">
                <div class="p-6 border-b" style="border-color: var(--border-color);">
                    <h3 class="text-lg font-semibold flex items-center" style="color: var(--text-primary);">
                        <i class="fas fa-info-circle mr-2" style="color: var(--primary);"></i>
                        Attendance Point Details
                    </h3>
                </div>
                <div class="p-6">
                    <div class="space-y-6">
                        <!-- Basic Info Grid -->
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div class="info-card p-4 rounded-lg" style="background-color: var(--bg-secondary);">
                                <label class="block text-xs font-medium uppercase tracking-wider mb-2" style="color: var(--text-secondary);">
                                    <i class="fas fa-tag mr-1" style="color: var(--info);"></i> Attendance Point Name
                                </label>
                                <div class="text-lg font-semibold" style="color: var(--text-primary);">{{ $qrCode->name }}</div>
                                <div class="text-sm mt-1" style="color: var(--text-secondary);">Location: {{ $post->name }}</div>
                            </div>

                            <div class="info-card p-4 rounded-lg" style="background-color: var(--bg-secondary);">
                                <label class="block text-xs font-medium uppercase tracking-wider mb-2" style="color: var(--text-secondary);">
                                    <i class="fas fa-qrcode mr-1" style="color: var(--info);"></i> QR Code Type
                                </label>
                                @php
                                    $isPermanent = $qrCode->code_type === 'static' && $qrCode->expires_at === null;
                                    $typeStyles = [
                                        'static' => [
                                            'bg' => $isPermanent ? 'rgba(var(--info-rgb), 0.1)' : 'rgba(var(--info-rgb), 0.1)',
                                            'text' => $isPermanent ? 'var(--info)' : 'var(--info)',
                                            'icon' => $isPermanent ? 'fa-infinity' : 'fa-qrcode',
                                            'label' => $isPermanent ? 'PERMANENT ATTENDANCE QR (Never Expires)' : 'Static Attendance QR'
                                        ],
                                        'one_time' => ['bg' => 'rgba(var(--warning-rgb), 0.1)', 'text' => 'var(--warning)', 'icon' => 'fa-clock', 'label' => 'ONE-TIME USE ATTENDANCE QR'],
                                        'time_based' => ['bg' => 'rgba(var(--danger-rgb), 0.1)', 'text' => 'var(--danger)', 'icon' => 'fa-hourglass-half', 'label' => 'TIME-LIMITED ATTENDANCE QR'],
                                    ];
                                    $style = $typeStyles[$qrCode->code_type] ?? ['bg' => 'rgba(var(--secondary-rgb), 0.1)', 'text' => 'var(--secondary)', 'icon' => 'fa-qrcode', 'label' => 'Unknown Type'];
                                @endphp
                                <div class="flex items-center">
                                    <span class="px-4 py-2 rounded-lg text-sm font-medium inline-flex items-center"
                                          style="background-color: {{ $style['bg'] }}; color: {{ $style['text'] }}; border: 1px solid {{ $style['text'] }};">
                                        <i class="fas {{ $style['icon'] }} mr-2"></i>
                                        {{ $style['label'] }}
                                    </span>
                                </div>
                            </div>
                        </div>

                        @if($qrCode->description)
                        <div class="info-card p-4 rounded-lg" style="background-color: var(--bg-secondary);">
                            <label class="block text-xs font-medium uppercase tracking-wider mb-2" style="color: var(--text-secondary);">
                                <i class="fas fa-align-left mr-1" style="color: var(--info);"></i> Location Description / Instructions
                            </label>
                            <div class="text-base" style="color: var(--text-primary);">{{ $qrCode->description }}</div>
                        </div>
                        @endif

                        <!-- Quick Access Instructions -->
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div class="p-4 rounded-lg text-center" style="background-color: var(--bg-secondary);">
                                <i class="fas fa-mobile-alt text-2xl mb-2" style="color: var(--success);"></i>
                                <h4 class="font-semibold mb-1" style="color: var(--text-primary);">Mobile Scanning</h4>
                                <p class="text-xs" style="color: var(--text-secondary);">Use the official attendance app on your mobile device</p>
                            </div>
                            <div class="p-4 rounded-lg text-center" style="background-color: var(--bg-secondary);">
                                <i class="fas fa-clock text-2xl mb-2" style="color: var(--warning);"></i>
                                <h4 class="font-semibold mb-1" style="color: var(--text-primary);">Scanning Hours</h4>
                                <p class="text-xs" style="color: var(--text-secondary);">
                                    @if($qrCode->expires_at)
                                        Valid until {{ \Carbon\Carbon::parse($qrCode->expires_at)->format('d M Y H:i') }}
                                    @else
                                        24/7 - Always available
                                    @endif
                                </p>
                            </div>
                        </div>

                        <!-- Status & Metrics Grid -->
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <!-- Status -->
                            <div class="info-card p-4 rounded-lg text-center" style="background-color: var(--bg-secondary);">
                                <label class="block text-xs font-medium uppercase tracking-wider mb-2" style="color: var(--text-secondary);">
                                    <i class="fas fa-circle mr-1" style="color: var(--info);"></i> QR Status
                                </label>
                                <button onclick="toggleStatus({{ $qrCode->id }}, {{ $qrCode->is_active ? 'false' : 'true' }})"
                                        class="px-4 py-2 rounded-lg text-sm font-medium inline-flex items-center transition-all duration-200 hover:scale-105 status-toggle"
                                        style="background-color: {{ $qrCode->is_active ? 'rgba(var(--success-rgb), 0.1)' : 'rgba(var(--danger-rgb), 0.1)' }}; 
                                               color: {{ $qrCode->is_active ? 'var(--success)' : 'var(--danger)' }};
                                               border: 1px solid {{ $qrCode->is_active ? 'var(--success)' : 'var(--danger)' }};">
                                    <i class="fas {{ $qrCode->is_active ? 'fa-check-circle' : 'fa-times-circle' }} mr-2"></i>
                                    {{ $qrCode->is_active ? 'Active - Ready for Scanning' : 'Inactive - Not Usable' }}
                                </button>
                                @if($qrCode->trashed())
                                    <span class="inline-block mt-2 px-3 py-1 rounded-full text-xs"
                                          style="background-color: rgba(var(--dark-rgb), 0.1); color: var(--dark); border: 1px solid rgba(var(--dark-rgb), 0.3);">
                                        <i class="fas fa-trash mr-1"></i> Deleted
                                    </span>
                                @endif
                            </div>

                            <!-- Total Scans / Uses -->
                            <div class="info-card p-4 rounded-lg" style="background-color: var(--bg-secondary);">
                                <label class="block text-xs font-medium uppercase tracking-wider mb-2" style="color: var(--text-secondary);">
                                    <i class="fas fa-chart-line mr-1" style="color: var(--info);"></i> Total Attendance Scans
                                </label>
                                <div class="text-2xl font-bold" style="color: var(--primary);">{{ $qrCode->uses_count }}</div>
                                @if($qrCode->max_uses)
                                    <div class="text-sm mt-1" style="color: var(--text-secondary);">of {{ $qrCode->max_uses }} maximum scans</div>
                                    @php
                                        $percentage = min(100, ($qrCode->uses_count / $qrCode->max_uses) * 100);
                                        $barColor = $percentage >= 100 ? 'var(--danger)' : ($percentage >= 75 ? 'var(--warning)' : 'var(--success)');
                                    @endphp
                                    <div class="w-full h-2 rounded-full mt-3" style="background-color: var(--border-color);">
                                        <div class="h-2 rounded-full transition-all duration-300" 
                                             style="width: {{ $percentage }}%; background-color: {{ $barColor }};"></div>
                                    </div>
                                @else
                                    <div class="text-sm mt-1" style="color: var(--text-secondary);">
                                        <i class="fas fa-infinity mr-1" style="color: var(--info);"></i> unlimited scans allowed
                                    </div>
                                @endif
                            </div>

                            <!-- Expiration -->
                            <div class="info-card p-4 rounded-lg" style="background-color: var(--bg-secondary);">
                                <label class="block text-xs font-medium uppercase tracking-wider mb-2" style="color: var(--text-secondary);">
                                    <i class="fas fa-hourglass-end mr-1" style="color: var(--info);"></i> QR Validity
                                </label>
                                
                                @php
                                    $isPermanent = $qrCode->code_type === 'static' && $qrCode->expires_at === null;
                                @endphp
                                
                                @if($isPermanent)
                                    <!-- PERMANENT QR CODE - NEVER EXPIRES -->
                                    <div class="text-base font-semibold flex items-center" style="color: var(--info);">
                                        <i class="fas fa-infinity mr-2"></i>
                                        <span>Permanent - Never Expires</span>
                                    </div>
                                    <span class="inline-block mt-2 px-3 py-1 text-xs rounded-full"
                                          style="background-color: rgba(var(--info-rgb), 0.1); color: var(--info); border: 1px solid rgba(var(--info-rgb), 0.3);">
                                        <i class="fas fa-infinity mr-1"></i> Always Available for Attendance
                                    </span>
                                    
                                @elseif($qrCode->expires_at)
                                    @php
                                        $expiresAt = \Carbon\Carbon::parse($qrCode->expires_at);
                                        $isExpired = $expiresAt->isPast();
                                        $expiresColor = $isExpired ? 'var(--danger)' : ($expiresAt->diffInDays(now()) <= 7 ? 'var(--warning)' : 'var(--success)');
                                    @endphp
                                    <div class="text-base font-semibold" style="color: {{ $expiresColor }};">
                                        <i class="fas fa-calendar-alt mr-1"></i>
                                        {{ $expiresAt->format('M d, Y') }}
                                    </div>
                                    <div class="text-sm mt-1" style="color: {{ $expiresColor }};">
                                        <i class="fas fa-clock mr-1"></i>
                                        {{ $expiresAt->format('H:i') }}
                                    </div>
                                    @if($isExpired)
                                        <span class="inline-block mt-2 px-2 py-1 text-xs rounded"
                                              style="background-color: rgba(var(--danger-rgb), 0.1); color: var(--danger);">
                                            <i class="fas fa-exclamation-circle mr-1"></i> EXPIRED - DO NOT USE
                                        </span>
                                    @else
                                        <span class="inline-block mt-2 px-2 py-1 text-xs rounded"
                                              style="background-color: rgba(var(--success-rgb), 0.1); color: var(--success);">
                                            <i class="fas fa-check-circle mr-1"></i> Valid for attendance until {{ $expiresAt->format('d M Y') }}
                                        </span>
                                    @endif
                                @endif
                            </div>
                        </div>

                        <!-- Location Verification -->
                        @if($post->latitude && $post->longitude)
                        <div class="p-4 rounded-lg" style="background-color: rgba(var(--success-rgb), 0.05); border: 1px solid rgba(var(--success-rgb), 0.2);">
                            <div class="flex items-center">
                                <i class="fas fa-map-marker-alt text-2xl mr-3" style="color: var(--success);"></i>
                                <div>
                                    <h4 class="font-semibold" style="color: var(--text-primary);">GPS Location Verified</h4>
                                    <p class="text-sm" style="color: var(--text-secondary);">
                                        This QR code will only work when scanned at {{ $post->name }} (GPS coordinates: {{ $post->latitude }}, {{ $post->longitude }})
                                    </p>
                                </div>
                            </div>
                        </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Usage Statistics Card (preserved) -->
    <div class="card">
        <div class="p-6 border-b" style="border-color: var(--border-color);">
            <h3 class="text-lg font-semibold flex items-center" style="color: var(--text-primary);">
                <i class="fas fa-chart-bar mr-2" style="color: var(--primary);"></i>
                Attendance Statistics
            </h3>
        </div>
        <div class="p-6">
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                <!-- Total Scans -->
                <div class="stat-card p-6 rounded-xl text-center transition-all duration-300 hover:scale-105 hover:shadow-lg"
                     style="background: linear-gradient(135deg, rgba(var(--primary-rgb), 0.05), rgba(var(--secondary-rgb), 0.05)); border: 1px solid rgba(var(--primary-rgb), 0.2);">
                    <div class="w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4"
                         style="background-color: rgba(var(--primary-rgb), 0.1);">
                        <i class="fas fa-user-check text-2xl" style="color: var(--primary);"></i>
                    </div>
                    <div class="text-3xl font-bold mb-2" style="color: var(--primary);">{{ $usageStats->total_uses ?? 0 }}</div>
                    <div class="text-sm font-medium" style="color: var(--text-secondary);">Total Attendance Records</div>
                </div>

                <!-- Unique Personnel -->
                <div class="stat-card p-6 rounded-xl text-center transition-all duration-300 hover:scale-105 hover:shadow-lg"
                     style="background: linear-gradient(135deg, rgba(var(--success-rgb), 0.05), rgba(var(--info-rgb), 0.05)); border: 1px solid rgba(var(--success-rgb), 0.2);">
                    <div class="w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4"
                         style="background-color: rgba(var(--success-rgb), 0.1);">
                        <i class="fas fa-users text-2xl" style="color: var(--success);"></i>
                    </div>
                    <div class="text-3xl font-bold mb-2" style="color: var(--success);">{{ $usageStats->unique_users ?? 0 }}</div>
                    <div class="text-sm font-medium" style="color: var(--text-secondary);">Unique Personnel</div>
                </div>

                <!-- Last Scan -->
                <div class="stat-card p-6 rounded-xl text-center transition-all duration-300 hover:scale-105 hover:shadow-lg"
                     style="background: linear-gradient(135deg, rgba(var(--warning-rgb), 0.05), rgba(var(--danger-rgb), 0.05)); border: 1px solid rgba(var(--warning-rgb), 0.2);">
                    <div class="w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4"
                         style="background-color: rgba(var(--warning-rgb), 0.1);">
                        <i class="fas fa-clock text-2xl" style="color: var(--warning);"></i>
                    </div>
                    <div class="text-2xl font-bold mb-2" style="color: var(--warning);">
                        @if($usageStats->last_used_at)
                            {{ \Carbon\Carbon::parse($usageStats->last_used_at)->diffForHumans() }}
                        @else
                            No scans yet
                        @endif
                    </div>
                    <div class="text-sm font-medium" style="color: var(--text-secondary);">Last Attendance Scan</div>
                </div>
            </div>
        </div>
    </div>

    <!-- Additional Information Card (preserved) -->
    <div class="card">
        <div class="p-6 border-b" style="border-color: var(--border-color);">
            <h3 class="text-lg font-semibold flex items-center" style="color: var(--text-primary);">
                <i class="fas fa-info-circle mr-2" style="color: var(--primary);"></i>
                Administrative Information
            </h3>
        </div>
        <div class="p-6">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <!-- Creation Info -->
                <div class="info-group p-4 rounded-lg" style="background-color: var(--bg-secondary);">
                    <h4 class="text-sm font-medium mb-3 flex items-center" style="color: var(--text-secondary);">
                        <i class="fas fa-calendar-plus mr-2" style="color: var(--success);"></i>
                        QR Code Created
                    </h4>
                    <div class="space-y-2">
                        <div class="flex justify-between">
                            <span style="color: var(--text-secondary);">Date:</span>
                            <span style="color: var(--text-primary);">{{ $qrCode->created_at->format('M d, Y H:i:s') }}</span>
                        </div>
                        <div class="flex justify-between">
                            <span style="color: var(--text-secondary);">By:</span>
                            <span style="color: var(--text-primary);">{{ $qrCode->creator->name ?? 'System' }}</span>
                        </div>
                    </div>
                </div>

                <!-- Update Info -->
                <div class="info-group p-4 rounded-lg" style="background-color: var(--bg-secondary);">
                    <h4 class="text-sm font-medium mb-3 flex items-center" style="color: var(--text-secondary);">
                        <i class="fas fa-calendar-check mr-2" style="color: var(--info);"></i>
                        Last Updated
                    </h4>
                    <div class="space-y-2">
                        <div class="flex justify-between">
                            <span style="color: var(--text-secondary);">Date:</span>
                            <span style="color: var(--text-primary);">{{ $qrCode->updated_at->format('M d, Y H:i:s') }}</span>
                        </div>
                        <div class="flex justify-between">
                            <span style="color: var(--text-secondary);">Time:</span>
                            <span style="color: var(--text-primary);">{{ $qrCode->updated_at->format('H:i:s') }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Regenerate Modal (preserved) -->
<div id="regenerateModal" class="modal hidden">
    <div class="modal-overlay" onclick="closeModal('regenerateModal')"></div>
    <div class="modal-container" style="max-width: 500px;">
        <div class="modal-header">
            <h3 class="text-lg font-semibold flex items-center" style="color: var(--text-primary);">
                <i class="fas fa-sync-alt mr-2" style="color: var(--warning);"></i>
                Regenerate Attendance QR Code
            </h3>
            <button onclick="closeModal('regenerateModal')" class="modal-close">
                <i class="fas fa-times" style="color: var(--text-secondary);"></i>
            </button>
        </div>
        <div class="modal-body p-6">
            <div class="text-center">
                <div class="w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4 animate-pulse"
                     style="background: linear-gradient(135deg, rgba(var(--warning-rgb), 0.2), rgba(var(--danger-rgb), 0.2));">
                    <i class="fas fa-sync-alt text-3xl" style="color: var(--warning);"></i>
                </div>
                <h4 class="text-xl font-semibold mb-2" style="color: var(--text-primary);" id="regenerateQrName"></h4>
                <p class="mb-6" style="color: var(--text-secondary);">
                    Regenerating will create a new attendance QR code. The old code will be permanently invalidated.
                </p>
                <div class="text-left mb-4">
                    <label class="block mb-2 text-sm font-medium" style="color: var(--text-primary);">
                        <i class="fas fa-pen mr-1" style="color: var(--info);"></i>
                        Reason for regeneration (Optional)
                    </label>
                    <input type="text" 
                           id="regenerateReason" 
                           class="w-full p-3 rounded-lg border transition-all duration-200 focus:ring-2"
                           style="border-color: var(--border-color); background-color: var(--card-bg); color: var(--text-primary);"
                           placeholder="e.g., Security rotation, Lost QR code, Regular renewal">
                </div>
                <div class="p-4 rounded-lg" style="background-color: rgba(var(--warning-rgb), 0.1); border: 1px solid rgba(var(--warning-rgb), 0.3);">
                    <div class="flex items-start">
                        <i class="fas fa-exclamation-triangle mr-2 mt-0.5" style="color: var(--warning);"></i>
                        <div class="text-sm text-left" style="color: var(--warning);">
                            <strong>Important:</strong> After regeneration, security personnel must use the NEW QR code for attendance. 
                            The old printed copies will no longer work.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer px-6 py-4 border-t" style="border-color: var(--border-color);">
            <div class="flex justify-end space-x-3">
                <button onclick="closeModal('regenerateModal')"
                        class="px-6 py-2 rounded-lg font-medium inline-flex items-center transition-all duration-200 hover:scale-105"
                        style="background-color: rgba(var(--secondary-rgb), 0.1); color: var(--secondary); border: 1px solid rgba(var(--secondary-rgb), 0.3);">
                    <i class="fas fa-times mr-2"></i>
                    Cancel
                </button>
                <form id="regenerateForm" method="POST" class="inline">
                    @csrf
                    <button type="submit"
                            class="px-6 py-2 rounded-lg font-medium inline-flex items-center text-white transition-all duration-200 hover:scale-105"
                            style="background: linear-gradient(135deg, var(--warning) 0%, var(--danger) 100%);">
                        <i class="fas fa-sync-alt mr-2"></i>
                        Regenerate Attendance QR
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete Modal (preserved) -->
<div id="deleteModal" class="modal hidden">
    <div class="modal-overlay" onclick="closeModal('deleteModal')"></div>
    <div class="modal-container" style="max-width: 500px;">
        <div class="modal-header">
            <h3 class="text-lg font-semibold flex items-center" style="color: var(--text-primary);">
                <i class="fas fa-trash mr-2" style="color: var(--danger);"></i>
                Delete Attendance QR Code
            </h3>
            <button onclick="closeModal('deleteModal')" class="modal-close">
                <i class="fas fa-times" style="color: var(--text-secondary);"></i>
            </button>
        </div>
        <div class="modal-body p-6">
            <div class="text-center">
                <div class="w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4"
                     style="background-color: rgba(var(--danger-rgb), 0.1);">
                    <i class="fas fa-trash text-3xl" style="color: var(--danger);"></i>
                </div>
                <h4 class="text-xl font-semibold mb-2" style="color: var(--text-primary);" id="deleteQrName"></h4>
                <p class="mb-6" style="color: var(--text-secondary);">
                    Are you sure you want to delete this attendance QR code? Security personnel will no longer be able to scan it for check-in/out.
                </p>
                <div class="p-4 rounded-lg" style="background-color: rgba(var(--danger-rgb), 0.1); border: 1px solid rgba(var(--danger-rgb), 0.3);">
                    <div class="flex items-start">
                        <i class="fas fa-exclamation-triangle mr-2 mt-0.5" style="color: var(--danger);"></i>
                        <div class="text-sm text-left" style="color: var(--danger);">
                            <strong>Warning:</strong> All printed copies of this QR code will stop working immediately. 
                            You will need to generate a new QR code for attendance tracking.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer px-6 py-4 border-t" style="border-color: var(--border-color);">
            <div class="flex justify-end space-x-3">
                <button onclick="closeModal('deleteModal')"
                        class="px-6 py-2 rounded-lg font-medium inline-flex items-center transition-all duration-200 hover:scale-105"
                        style="background-color: rgba(var(--secondary-rgb), 0.1); color: var(--secondary); border: 1px solid rgba(var(--secondary-rgb), 0.3);">
                    <i class="fas fa-times mr-2"></i>
                    Cancel
                </button>
                <form id="deleteForm" method="POST" class="inline">
                    @csrf
                    @method('DELETE')
                    <button type="submit"
                            class="px-6 py-2 rounded-lg font-medium inline-flex items-center text-white transition-all duration-200 hover:scale-105"
                            style="background-color: var(--danger); border: 1px solid var(--danger);">
                        <i class="fas fa-trash mr-2"></i>
                        Delete QR Code
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Toast Container (preserved) -->
<div id="toast-container" class="fixed top-4 right-4 z-50 space-y-2"></div>

<!-- Loading Overlay (preserved) -->
<div id="loadingOverlay" class="loading-overlay hidden">
    <div class="text-center">
        <div class="inline-block animate-spin rounded-full h-12 w-12 border-4 border-t-transparent mb-4"
             style="border-color: var(--primary); border-top-color: transparent;"></div>
        <div class="text-white font-medium" id="loadingMessage">Processing...</div>
    </div>
</div>

<!-- Print Styles (preserved) -->
<style media="print">
    @page {
        size: A4;
        margin: 1cm;
    }
    
    body * {
        visibility: hidden;
    }
    
    .card, .modal, .modal-overlay, .action-btn, button, a.btn {
        display: none !important;
    }
    
    #qr-code-print-area, #qr-code-print-area * {
        visibility: visible;
    }
    
    #qr-code-print-area {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        padding: 20px;
        text-align: center;
    }
    
    .print-only {
        display: block !important;
    }
</style>

<!-- Hidden Print Area (preserved) -->
<div id="qr-code-print-area" class="hidden print-only">
    <div style="text-align: center; padding: 20px; font-family: Arial, sans-serif;">
        <h1 style="color: #333; margin-bottom: 10px;">ATTENDANCE CHECK-IN/OUT QR CODE</h1>
        <h2 style="color: #666; margin-bottom: 30px;">{{ $post->name }} ({{ $post->code }})</h2>
        
        <div style="margin: 30px auto; max-width: 300px;">
            @if($qrCode->image_path)
                <img src="{{ asset('storage/' . $qrCode->image_path) }}" alt="Attendance QR Code" style="width: 100%; height: auto;">
            @endif
        </div>
        
        <div style="margin-top: 30px; text-align: left; border-top: 2px solid #333; padding-top: 20px;">
            <h3 style="color: #333; margin-bottom: 15px;">📋 INSTRUCTIONS FOR SECURITY PERSONNEL:</h3>
            
            <div style="margin-bottom: 20px;">
                <h4 style="color: #444; margin-bottom: 10px;">✅ CHECK-IN PROCEDURE:</h4>
                <ol style="margin-left: 20px; color: #555; line-height: 1.6;">
                    <li>Open the official attendance scanning app on your mobile device</li>
                    <li>Select "CHECK-IN" mode from the main menu</li>
                    <li>Scan this QR code when personnel arrive at {{ $post->name }}</li>
                    <li>Verify that the scanner shows "CHECK-IN SUCCESSFUL"</li>
                    <li>Confirm personnel details appear correctly on screen</li>
                </ol>
            </div>
            
            <div style="margin-bottom: 20px;">
                <h4 style="color: #444; margin-bottom: 10px;">⬆️ CHECK-OUT PROCEDURE:</h4>
                <ol style="margin-left: 20px; color: #555; line-height: 1.6;">
                    <li>Switch the app to "CHECK-OUT" mode</li>
                    <li>Scan the same QR code when personnel are leaving</li>
                    <li>Verify that the scanner shows "CHECK-OUT SUCCESSFUL"</li>
                    <li>Confirm total hours worked are displayed correctly</li>
                </ol>
            </div>
            
            <div style="margin-top: 20px; padding: 15px; background-color: #f8f8f8; border-left: 4px solid #ff6b6b;">
                <p style="margin: 0; color: #444; font-size: 14px;">
                    <strong>⚠️ IMPORTANT NOTES:</strong><br>
                    • Only scan at {{ $post->name }} attendance point<br>
                    • Ensure good lighting for successful scanning<br>
                    • Do not share this QR code with unauthorized personnel<br>
                    • Contact supervisor immediately if scanner shows errors<br>
                    • This QR code is for {{ $post->name }} only
                </p>
            </div>
            
            <div style="margin-top: 30px; font-size: 12px; color: #999; text-align: center;">
                <p>QR Code ID: {{ $qrCode->code }} | Generated: {{ $qrCode->created_at->format('Y-m-d H:i') }}</p>
                <p>This QR code is valid for attendance tracking at {{ $post->name }}</p>
            </div>
        </div>
    </div>
</div>

<!-- Alpine.js for dropdown functionality -->
<script src="//unpkg.com/alpinejs" defer></script>

<style>
/* Info Card Styles */
.info-card {
    transition: all 0.3s ease;
    border: 1px solid var(--border-color);
}

.info-card:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    border-color: var(--primary);
}

/* Stat Card Styles */
.stat-card {
    position: relative;
    overflow: hidden;
}

.stat-card::before {
    content: '';
    position: absolute;
    top: -50%;
    left: -50%;
    width: 200%;
    height: 200%;
    background: linear-gradient(
        45deg,
        transparent 30%,
        rgba(255, 255, 255, 0.1) 50%,
        transparent 70%
    );
    transform: rotate(45deg);
    animation: shimmer 3s infinite;
    pointer-events: none;
}

@keyframes shimmer {
    0% { transform: translateX(-100%) rotate(45deg); }
    100% { transform: translateX(100%) rotate(45deg); }
}

/* Action Button Styles */
.action-btn {
    transition: all 0.2s ease;
    cursor: pointer;
    border: none;
}

.action-btn:hover {
    transform: translateY(-2px) scale(1.1);
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

/* Copy Button Animation */
.copy-btn {
    animation: pulse 2s infinite;
}

@keyframes pulse {
    0% { box-shadow: 0 0 0 0 rgba(var(--primary-rgb), 0.7); }
    70% { box-shadow: 0 0 0 10px rgba(var(--primary-rgb), 0); }
    100% { box-shadow: 0 0 0 0 rgba(var(--primary-rgb), 0); }
}

/* Status Toggle Button */
.status-toggle {
    transition: all 0.2s ease;
    cursor: pointer;
}

.status-toggle:hover {
    filter: brightness(1.1);
    transform: scale(1.05);
}

/* Modal Styles */
.modal {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 9999;
    display: flex;
    align-items: center;
    justify-content: center;
}

.modal.hidden {
    display: none;
}

.modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.5);
    animation: fadeIn 0.2s ease;
}

.modal-container {
    position: relative;
    background-color: var(--card-bg);
    border-radius: 1rem;
    box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
    width: 90%;
    max-width: 500px;
    max-height: 90vh;
    overflow-y: auto;
    z-index: 10000;
    animation: slideUp 0.3s ease;
}

@keyframes slideUp {
    from { opacity: 0; transform: translateY(20px); }
    to { opacity: 1; transform: translateY(0); }
}

@keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
}

.modal-header {
    padding: 1.5rem;
    border-bottom: 1px solid var(--border-color);
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.modal-close {
    width: 32px;
    height: 32px;
    border-radius: 6px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: transparent;
    border: none;
    cursor: pointer;
    transition: all 0.2s ease;
}

.modal-close:hover {
    background-color: rgba(var(--danger-rgb), 0.1);
    transform: rotate(90deg);
}

.modal-close:hover i {
    color: var(--danger) !important;
}

/* Loading Overlay */
.loading-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.75);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 10001;
    animation: fadeIn 0.2s ease;
}

.loading-overlay.hidden {
    display: none;
}

/* Toast Container */
#toast-container {
    z-index: 10002;
}

#toast-container > div {
    animation: slideInRight 0.3s ease;
    transition: transform 0.3s ease;
}

@keyframes slideInRight {
    from { opacity: 0; transform: translateX(100%); }
    to { opacity: 1; transform: translateX(0); }
}

/* Print styles */
@media print {
    .no-print {
        display: none !important;
    }
    
    .print-only {
        display: block !important;
    }
    
    .print-area {
        visibility: visible !important;
    }
}

/* Responsive Adjustments */
@media (max-width: 768px) {
    .grid-cols-1.lg\:grid-cols-3 {
        grid-template-columns: 1fr;
    }
    
    .modal-container {
        width: 95%;
        margin: 1rem;
    }
    
    .action-btn {
        width: 36px;
        height: 36px;
    }
}

@media (max-width: 640px) {
    .flex.items-center.space-x-2 {
        flex-direction: column;
        space-x: 0;
        space-y: 2;
        width: 100%;
    }
    
    .flex.items-center.space-x-2 a,
    .flex.items-center.space-x-2 button {
        width: 100%;
        justify-content: center;
    }
    
    .stat-card {
        padding: 1rem;
    }
}
</style>
@endsection

@push('scripts')
<script>
let currentQrId = null;

// Copy to clipboard function
function copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(function() {
        showToast('QR code copied to clipboard!', 'success');
    }).catch(function(err) {
        console.error('Copy error:', err);
        showToast('Failed to copy QR code', 'error');
    });
}

// Toggle QR Code Status
async function toggleStatus(qrId, newStatus) {
    if (!confirm(`Are you sure you want to ${newStatus ? 'activate' : 'deactivate'} this attendance QR code?`)) {
        return;
    }
    
    showLoading('Updating QR code status...');
    
    try {
        const response = await fetch(`/admin/security-posts/{{ $post->id }}/qr-codes/${qrId}/update-status`, {
            method: 'POST',
            headers: {
                'X-CSRF-TOKEN': '{{ csrf_token() }}',
                'Content-Type': 'application/json',
                'Accept': 'application/json',
                'X-Requested-With': 'XMLHttpRequest'
            },
            body: JSON.stringify({
                is_active: newStatus,
                reason: `Manual ${newStatus ? 'activation' : 'deactivation'} from details page`
            })
        });
        
        // Check if response is OK
        if (!response.ok) {
            throw new Error(`Server error: ${response.status}`);
        }
        
        // Check content type
        const contentType = response.headers.get('content-type');
        if (!contentType || !contentType.includes('application/json')) {
            throw new Error('Invalid response format from server');
        }
        
        const data = await response.json();
        hideLoading();
        
        if (data.success) {
            showToast(data.message, 'success');
            setTimeout(() => location.reload(), 1500);
        } else {
            showToast(data.message || 'Failed to update status', 'error');
        }
    } catch (error) {
        hideLoading();
        console.error('Toggle Status Error:', error);
        showToast(error.message || 'Network error occurred', 'error');
    }
}

// Modal Functions
function showRegenerateModal(qrId, qrName) {
    currentQrId = qrId;
    document.getElementById('regenerateQrName').textContent = qrName;
    document.getElementById('regenerateReason').value = '';
    
    const regenerateForm = document.getElementById('regenerateForm');
    regenerateForm.action = `/admin/security-posts/{{ $post->id }}/qr-codes/${qrId}/regenerate`;
    
    openModal('regenerateModal');
}

function showDeleteModal(qrId, qrName) {
    currentQrId = qrId;
    document.getElementById('deleteQrName').textContent = qrName;
    
    const deleteForm = document.getElementById('deleteForm');
    deleteForm.action = `/admin/security-posts/{{ $post->id }}/qr-codes/${qrId}`;
    
    openModal('deleteModal');
}

function openModal(modalId) {
    const modal = document.getElementById(modalId);
    if (modal) {
        modal.classList.remove('hidden');
        document.body.style.overflow = 'hidden';
    }
}

function closeModal(modalId) {
    const modal = document.getElementById(modalId);
    if (modal) {
        modal.classList.add('hidden');
        document.body.style.overflow = 'auto';
    }
}

// Print function
function printQRCode() {
    window.print();
}

// Handle regenerate form submission - FIXED VERSION
document.addEventListener('DOMContentLoaded', function() {
    const regenerateForm = document.getElementById('regenerateForm');
    if (regenerateForm) {
        regenerateForm.addEventListener('submit', function(e) {
            e.preventDefault();
            
            const reason = document.getElementById('regenerateReason').value;
            const formData = new FormData(this);
            
            if (reason) {
                formData.append('reason', reason);
            }
            
            showLoading('Regenerating attendance QR code...');
            
            // FIXED: Added proper headers for AJAX
            fetch(this.action, {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}',
                    'Accept': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
            .then(async response => {
                // Check if response is OK
                if (!response.ok) {
                    throw new Error(`Server error: ${response.status}`);
                }
                
                // Check content type
                const contentType = response.headers.get('content-type');
                if (contentType && contentType.includes('application/json')) {
                    return await response.json();
                } else {
                    // If not JSON, check if it's a redirect
                    const text = await response.text();
                    
                    // Check for meta refresh redirect
                    const metaMatch = text.match(/url=([^"']+)/i);
                    if (metaMatch) {
                        window.location.href = metaMatch[1];
                        return { success: true, redirect: metaMatch[1] };
                    }
                    
                    // Check for JavaScript redirect
                    if (text.includes('window.location') || text.includes('location.href')) {
                        // Page will redirect, we can just reload
                        setTimeout(() => window.location.reload(), 100);
                        return { success: true };
                    }
                    
                    throw new Error('Unexpected response format from server');
                }
            })
            .then(data => {
                hideLoading();
                closeModal('regenerateModal');
                
                if (data.success) {
                    showToast(data.message || 'QR code regenerated successfully!', 'success');
                    
                    // Handle redirect if provided
                    if (data.redirect) {
                        setTimeout(() => {
                            window.location.href = data.redirect;
                        }, 1500);
                    } else {
                        // Refresh to show updated QR code
                        setTimeout(() => {
                            window.location.reload();
                        }, 1500);
                    }
                } else {
                    showToast(data.message || 'Failed to regenerate QR code', 'error');
                }
            })
            .catch(error => {
                hideLoading();
                console.error('Regenerate Error:', error);
                showToast(error.message || 'Network error occurred', 'error');
            });
        });
    }

    // Handle delete form submission - ADDED FOR COMPLETENESS
    const deleteForm = document.getElementById('deleteForm');
    if (deleteForm) {
        deleteForm.addEventListener('submit', function(e) {
            e.preventDefault();
            
            showLoading('Deleting QR code...');
            
            fetch(this.action, {
                method: 'POST',
                body: new FormData(this),
                headers: {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}',
                    'Accept': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
            .then(async response => {
                if (!response.ok) {
                    throw new Error(`Server error: ${response.status}`);
                }
                
                const contentType = response.headers.get('content-type');
                if (contentType && contentType.includes('application/json')) {
                    return await response.json();
                } else {
                    // Handle redirect
                    const text = await response.text();
                    if (response.redirected || text.includes('window.location')) {
                        setTimeout(() => window.location.reload(), 100);
                        return { success: true };
                    }
                    throw new Error('Unexpected response format');
                }
            })
            .then(data => {
                hideLoading();
                closeModal('deleteModal');
                
                if (data.success) {
                    showToast(data.message || 'QR code deleted successfully', 'success');
                    setTimeout(() => {
                        window.location.href = '{{ route("admin.security-posts.qr-codes.index", $post->id) }}';
                    }, 1500);
                } else {
                    showToast(data.message || 'Failed to delete QR code', 'error');
                }
            })
            .catch(error => {
                hideLoading();
                console.error('Delete Error:', error);
                showToast(error.message || 'Network error occurred', 'error');
            });
        });
    }
});

// Close modal when clicking outside
document.addEventListener('click', function(e) {
    if (e.target.classList.contains('modal-overlay')) {
        const modal = e.target.closest('.modal');
        if (modal) {
            modal.classList.add('hidden');
            document.body.style.overflow = 'auto';
        }
    }
});

// Close modal with Escape key
document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') {
        const modals = document.querySelectorAll('.modal');
        modals.forEach(modal => {
            if (!modal.classList.contains('hidden')) {
                modal.classList.add('hidden');
                document.body.style.overflow = 'auto';
            }
        });
    }
});

// Toast notification - ENHANCED with null checks
function showToast(message, type = 'info') {
    const container = document.getElementById('toast-container');
    if (!container) {
        console.warn('Toast container not found');
        return;
    }
    
    const toast = document.createElement('div');
    
    const colors = {
        success: { bg: 'rgba(var(--success-rgb), 0.1)', text: 'var(--success)', border: 'rgba(var(--success-rgb), 0.3)', icon: 'fa-check-circle' },
        error: { bg: 'rgba(var(--danger-rgb), 0.1)', text: 'var(--danger)', border: 'rgba(var(--danger-rgb), 0.3)', icon: 'fa-exclamation-circle' },
        warning: { bg: 'rgba(var(--warning-rgb), 0.1)', text: 'var(--warning)', border: 'rgba(var(--warning-rgb), 0.3)', icon: 'fa-exclamation-triangle' },
        info: { bg: 'rgba(var(--info-rgb), 0.1)', text: 'var(--info)', border: 'rgba(var(--info-rgb), 0.3)', icon: 'fa-info-circle' }
    };
    
    const color = colors[type] || colors.info;
    
    toast.className = 'px-4 py-3 rounded-lg shadow-lg flex items-center justify-between min-w-64 max-w-md transition-all duration-300 transform translate-x-full';
    toast.style.backgroundColor = color.bg;
    toast.style.color = color.text;
    toast.style.border = `1px solid ${color.border}`;
    toast.style.marginBottom = '0.5rem';
    toast.style.zIndex = '10002';
    
    toast.innerHTML = `
        <div class="flex items-center">
            <i class="fas ${color.icon} mr-2"></i>
            <span class="text-sm font-medium">${message}</span>
        </div>
        <button onclick="this.parentElement.remove()" class="ml-4 hover:opacity-75">
            <i class="fas fa-times"></i>
        </button>
    `;
    
    container.appendChild(toast);
    
    // Animate in
    setTimeout(() => toast.classList.remove('translate-x-full'), 10);
    
    // Auto remove after 5 seconds
    setTimeout(() => {
        if (toast.parentNode) {
            toast.classList.add('translate-x-full');
            setTimeout(() => {
                if (toast.parentNode) {
                    toast.remove();
                }
            }, 300);
        }
    }, 5000);
}

// Loading overlay - ENHANCED with null checks
function showLoading(message = 'Processing...') {
    const overlay = document.getElementById('loadingOverlay');
    const messageEl = document.getElementById('loadingMessage');
    
    if (messageEl) {
        messageEl.textContent = message;
    }
    
    if (overlay) {
        overlay.classList.remove('hidden');
    } else {
        console.warn('Loading overlay not found');
    }
}

function hideLoading() {
    const overlay = document.getElementById('loadingOverlay');
    if (overlay) {
        overlay.classList.add('hidden');
    }
}

// Tooltip initialization - ENHANCED with null checks
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('[data-tooltip]').forEach(element => {
        let tooltipTimeout;
        
        element.addEventListener('mouseenter', function() {
            const tooltip = this.nextElementSibling;
            if (tooltip) {
                tooltipTimeout = setTimeout(() => {
                    tooltip.classList.remove('hidden');
                }, 300);
            }
        });
        
        element.addEventListener('mouseleave', function() {
            clearTimeout(tooltipTimeout);
            const tooltip = this.nextElementSibling;
            if (tooltip) {
                tooltip.classList.add('hidden');
            }
        });
    });
    
    console.log('Attendance QR Code details page loaded');
});

// Add global error handler for unhandled promises
window.addEventListener('unhandledrejection', function(event) {
    console.error('Unhandled promise rejection:', event.reason);
    hideLoading();
    showToast('An unexpected error occurred', 'error');
});
</script>
@endpush