<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Ensure emails.user_email_account_id exists, is indexed,
     * and is properly constrained to user_email_accounts.
     *
     * Made idempotent so it's safe to re-run.
     */
    public function up(): void
    {
        // ── Step 1: Add the column if it doesn't exist ────────────────
        if (!Schema::hasColumn('emails', 'user_email_account_id')) {
            Schema::table('emails', function (Blueprint $table) {
                $table->foreignId('user_email_account_id')
                      ->nullable()
                      ->after('id')
                      ->constrained('user_email_accounts')
                      ->cascadeOnDelete();
            });

            return; // done — nothing else needed
        }

        // ── Step 2: Column exists — make sure it's correct ────────────
        // We do this in raw SQL because Laravel's ->change() on a
        // foreignId can't add/remove FK constraints in one step.

        $driver = DB::getDriverName();

        if ($driver === 'mysql') {
            // Drop any existing FK first (name is auto-generated by Laravel)
            $fkName = $this->getExistingForeignKeyName();

            if ($fkName) {
                DB::statement("ALTER TABLE `emails` DROP FOREIGN KEY `{$fkName}`");
            }

            // Make nullable + ensure signed bigint
            DB::statement("
                ALTER TABLE `emails`
                MODIFY `user_email_account_id` BIGINT UNSIGNED NULL
            ");

            // Re-add FK with cascade delete
            DB::statement("
                ALTER TABLE `emails`
                ADD CONSTRAINT `emails_user_email_account_id_foreign`
                FOREIGN KEY (`user_email_account_id`)
                REFERENCES `user_email_accounts` (`id`)
                ON DELETE CASCADE
            ");
        }

        // ── Step 3: Ensure index exists ───────────────────────────────
        if (!$this->indexExists('emails', 'emails_user_email_account_id_foreign')) {
            Schema::table('emails', function (Blueprint $table) {
                $table->index('user_email_account_id', 'emails_user_email_account_id_index');
            });
        }

        // ── Step 4: Optional — dedupe unique constraint ───────────────
        // Prevents the same IMAP message being stored twice.
        if (!$this->indexExists('emails', 'emails_account_message_unique')) {
            // Clean any existing duplicates first
            DB::statement("
                DELETE e1 FROM `emails` e1
                INNER JOIN `emails` e2
                WHERE e1.id > e2.id
                  AND e1.user_email_account_id = e2.user_email_account_id
                  AND e1.message_id = e2.message_id
                  AND e1.message_id IS NOT NULL
            ");

            Schema::table('emails', function (Blueprint $table) {
                $table->unique(
                    ['user_email_account_id', 'message_id'],
                    'emails_account_message_unique'
                );
            });
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        if (!Schema::hasColumn('emails', 'user_email_account_id')) {
            return;
        }

        // Drop unique index
        if ($this->indexExists('emails', 'emails_account_message_unique')) {
            Schema::table('emails', function (Blueprint $table) {
                $table->dropUnique('emails_account_message_unique');
            });
        }

        // Drop FK + column
        $driver = DB::getDriverName();

        if ($driver === 'mysql') {
            $fkName = $this->getExistingForeignKeyName();
            if ($fkName) {
                DB::statement("ALTER TABLE `emails` DROP FOREIGN KEY `{$fkName}`");
            }
        }

        Schema::table('emails', function (Blueprint $table) {
            $table->dropColumn('user_email_account_id');
        });
    }

    /**
     * Look up the actual FK constraint name from information_schema.
     * Laravel's default naming may differ from what's actually in the DB.
     */
    private function getExistingForeignKeyName(): ?string
    {
        $db = DB::getDatabaseName();

        $row = DB::selectOne("
            SELECT CONSTRAINT_NAME
            FROM information_schema.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = ?
              AND TABLE_NAME = 'emails'
              AND COLUMN_NAME = 'user_email_account_id'
              AND REFERENCED_TABLE_NAME IS NOT NULL
            LIMIT 1
        ", [$db]);

        return $row->CONSTRAINT_NAME ?? null;
    }

    /**
     * Check if a named index exists.
     */
    private function indexExists(string $table, string $indexName): bool
    {
        $db = DB::getDatabaseName();

        $row = DB::selectOne("
            SELECT COUNT(*) AS cnt
            FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = ?
              AND TABLE_NAME = ?
              AND INDEX_NAME = ?
        ", [$db, $table, $indexName]);

        return ($row->cnt ?? 0) > 0;
    }
};