<?php

namespace App\Http\Controllers;

use App\Models\LandlordInvitation;
use App\Models\Property;
use App\Models\User;
use App\Models\SystemSetting; // ✅ ADDED: Import SystemSetting model
use App\Services\MultiChannelInvitationService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;

class LandlordInvitationController extends Controller
{
    protected $multiChannelInvitationService;

    public function __construct(MultiChannelInvitationService $multiChannelInvitationService)
    {
        $this->multiChannelInvitationService = $multiChannelInvitationService;
    }

    /**
     * ✅ UPDATED: Store a newly created landlord invitation with token support
     * This is now primarily called from PropertyController during property registration
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'property_id' => 'required|exists:properties,id',
            'landlord_id' => 'required|exists:users,id',
            'channels' => 'required|array',
            'channels.*' => 'in:email,sms,whatsapp',
            'invitation_type' => 'required|in:registration,property_added,welcome',
            'custom_message' => 'nullable|string|max:500',
            'expires_in_days' => 'nullable|integer|min:1|max:30'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => 'Validation failed',
                'errors' => $validator->errors()
            ], 422);
        }

        DB::beginTransaction();

        try {
            // ✅ UPDATED: Check if landlord already has an active invitation for this property
            $existingInvitation = LandlordInvitation::where('property_id', $request->property_id)
                ->where('landlord_id', $request->landlord_id)
                ->whereIn('status', [
                    LandlordInvitation::STATUS_PENDING,
                    LandlordInvitation::STATUS_SENT
                ])
                ->where('expires_at', '>', now())
                ->first();

            if ($existingInvitation) {
                return response()->json([
                    'success' => false,
                    'message' => 'This landlord already has an active invitation for this property.',
                    'existing_invitation_id' => $existingInvitation->id
                ], 409);
            }

            // ✅ FIXED: Create the invitation (token is automatically generated by model)
            $invitation = LandlordInvitation::create([
                'property_id' => $request->property_id,
                'landlord_id' => $request->landlord_id,
                'invited_by' => auth()->id(),
                'channels' => $request->channels,
                'invitation_type' => $request->invitation_type,
                'custom_message' => $request->custom_message,
                'expires_at' => now()->addDays($request->expires_in_days ?? 7)
                // Token is automatically generated by model boot method
            ]);

            // ✅ ENHANCED: Log invitation creation with token
            Log::info('Landlord invitation created', [
                'invitation_id' => $invitation->id,
                'property_id' => $request->property_id,
                'landlord_id' => $request->landlord_id,
                'token' => $invitation->token,
                'invitation_url' => $invitation->getInvitationUrl(),
                'created_by' => auth()->id()
            ]);

            // Send the invitation
            $sendResult = $this->sendInvitation($invitation);

            DB::commit();

            $responseData = [
                'success' => $sendResult['success'],
                'message' => $sendResult['success'] ? 
                    'Landlord invitation created and sent successfully!' : 
                    'Invitation created but failed to send: ' . $sendResult['message'],
                'invitation_id' => $invitation->id,
                'token' => $invitation->token,
                'invitation_url' => $invitation->getInvitationUrl(),
                'send_result' => $sendResult
            ];

            return response()->json($responseData, $sendResult['success'] ? 201 : 200);

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Failed to create landlord invitation: ' . $e->getMessage(), [
                'property_id' => $request->property_id ?? 'unknown',
                'landlord_id' => $request->landlord_id ?? 'unknown',
                'user_id' => auth()->id()
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Failed to create landlord invitation. Please try again.',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * ✅ UPDATED: Resend a landlord invitation with improved token handling
     * This is typically called from the property show page
     */
    public function resend(Request $request, LandlordInvitation $landlordInvitation)
    {
        $validator = Validator::make($request->all(), [
            'channels' => 'sometimes|array',
            'channels.*' => 'in:email,sms,whatsapp',
            'custom_message' => 'nullable|string|max:500',
            'expires_in_days' => 'nullable|integer|min:1|max:30'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => 'Validation failed',
                'errors' => $validator->errors()
            ], 422);
        }

        DB::beginTransaction();

        try {
            // ✅ ENHANCED: Update invitation with new data
            $updateData = [];
            
            if ($request->has('channels')) {
                $updateData['channels'] = $request->channels;
            }
            
            if ($request->has('custom_message')) {
                $updateData['custom_message'] = $request->custom_message;
            }

            if ($request->has('expires_in_days')) {
                $updateData['expires_at'] = now()->addDays($request->expires_in_days);
            }
            
            if (!empty($updateData)) {
                $landlordInvitation->update($updateData);
            }

            // ✅ FIXED: Reset to pending status for resend
            $landlordInvitation->resend($request->channels ?? []);

            // Resend the invitation
            $sendResult = $this->sendInvitation($landlordInvitation);

            DB::commit();

            // ✅ ENHANCED: Better response with invitation details
            if ($sendResult['success']) {
                Log::info('Landlord invitation resent successfully', [
                    'invitation_id' => $landlordInvitation->id,
                    'token' => $landlordInvitation->token,
                    'channels' => $sendResult['channels_successful'] ?? []
                ]);

                return response()->json([
                    'success' => true,
                    'message' => 'Landlord invitation resent successfully!',
                    'invitation_url' => $landlordInvitation->getInvitationUrl(),
                    'token' => $landlordInvitation->token,
                    'send_result' => $sendResult
                ]);
            } else {
                Log::error('Failed to resend landlord invitation', [
                    'invitation_id' => $landlordInvitation->id,
                    'token' => $landlordInvitation->token,
                    'error' => $sendResult['message']
                ]);

                return response()->json([
                    'success' => false,
                    'message' => 'Failed to resend invitation: ' . $sendResult['message'],
                    'invitation_url' => $landlordInvitation->getInvitationUrl(),
                    'token' => $landlordInvitation->token,
                    'send_result' => $sendResult
                ], 500);
            }

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Failed to resend landlord invitation: ' . $e->getMessage(), [
                'invitation_id' => $landlordInvitation->id,
                'token' => $landlordInvitation->token
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Failed to resend landlord invitation. Please try again.',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * ✅ UPDATED: Cancel a landlord invitation
     */
    public function cancel(LandlordInvitation $landlordInvitation)
    {
        DB::beginTransaction();

        try {
            $landlordInvitation->update([
                'status' => LandlordInvitation::STATUS_CANCELLED
            ]);

            // ✅ ADDED: Log cancellation with token
            Log::info('Landlord invitation cancelled', [
                'invitation_id' => $landlordInvitation->id,
                'token' => $landlordInvitation->token,
                'cancelled_by' => auth()->id()
            ]);

            DB::commit();

            return response()->json([
                'success' => true,
                'message' => 'Landlord invitation cancelled successfully.'
            ]);

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Failed to cancel landlord invitation: ' . $e->getMessage(), [
                'invitation_id' => $landlordInvitation->id,
                'token' => $landlordInvitation->token
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Failed to cancel landlord invitation. Please try again.',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * ✅ FIXED: Accept landlord invitation (for landlords) with token validation
     * Now includes systemSettings to fix the Blade template error
     */
    public function accept(Request $request, $token)
    {
        // ✅ FIXED: Use the model's token-based finder method
        $invitation = LandlordInvitation::findByToken($token);
        
        if (!$invitation) {
            return redirect()->route('login')
                ->with('error', 'Invalid invitation link. Please check the URL or request a new invitation.');
        }

        // Check if invitation is valid
        if ($invitation->isExpired()) {
            return redirect()->route('login')
                ->with('error', 'This invitation link has expired. Please request a new one.');
        }

        if ($invitation->status === LandlordInvitation::STATUS_CANCELLED) {
            return redirect()->route('login')
                ->with('error', 'This invitation has been cancelled.');
        }

        if ($invitation->status === LandlordInvitation::STATUS_ACCEPTED) {
            return redirect()->route('login')
                ->with('info', 'This invitation has already been accepted.');
        }

        // If landlord is already logged in, verify it's the correct user
        if (auth()->check() && auth()->id() !== $invitation->landlord_id) {
            auth()->logout();
            return redirect()->route('landlord.invitations.accept', ['token' => $token])
                ->with('error', 'Please login with the correct landlord account to accept this invitation.');
        }

        // ✅ ADDED: Get system settings to fix the Blade template error
        $systemSettings = SystemSetting::first();
        
        // ✅ ADDED: Provide default system settings if not found
        if (!$systemSettings) {
            $systemSettings = (object) [
                'system_name' => 'Property Management System',
                'system_logo' => null,
                'support_email' => 'support@example.com',
                'system_phone' => null,
                'support_email' => 'support@example.com',
            ];
        }

        // ✅ ADDED: Log invitation access
        Log::info('Landlord accessed invitation acceptance form', [
            'invitation_id' => $invitation->id,
            'token' => $invitation->token,
            'landlord_id' => $invitation->landlord_id,
            'ip_address' => $request->ip()
        ]);

        // ✅ FIXED: Show acceptance form with systemSettings variable
        return view('landlord.invitations.accept', [
            'invitation' => $invitation,
            'token' => $token,
            'systemSettings' => $systemSettings // ✅ This fixes the error
        ]);
    }

    /**
     * ✅ UPDATED: Process invitation acceptance with enhanced security
     */
    public function processAcceptance(Request $request, $token)
    {
        // ✅ FIXED: Use the model's token-based finder method
        $invitation = LandlordInvitation::findByToken($token);
        
        if (!$invitation) {
            return redirect()->route('login')
                ->with('error', 'Invalid invitation token. Please request a new invitation.');
        }

        // Validate invitation
        if (!$invitation->isActive()) {
            return redirect()->route('login')
                ->with('error', 'This invitation is no longer valid.');
        }

        $validator = Validator::make($request->all(), [
            'password' => 'required|min:8|confirmed',
            'agree_terms' => 'required|accepted',
            'phone' => 'sometimes|required|string|max:20'
        ]);

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput()
                ->with('token', $token);
        }

        DB::beginTransaction();

        try {
            $landlord = $invitation->landlord;

            // ✅ FIXED: Use Hash facade for password hashing
            $updateData = [
                'password' => Hash::make($request->password),
                'is_active' => true,
                'email_verified_at' => $landlord->email_verified_at ?? now()
            ];

            if ($request->filled('phone')) {
                $updateData['phone'] = $request->phone;
            }

            $landlord->update($updateData);

            // Mark invitation as accepted
            $invitation->markAsAccepted();

            // ✅ ENHANCED: Log the acceptance with more details
            Log::info('Landlord invitation accepted successfully', [
                'invitation_id' => $invitation->id,
                'token' => $invitation->token,
                'landlord_id' => $landlord->id,
                'property_id' => $invitation->property_id,
                'accepted_at' => now()->toISOString(),
                'ip_address' => $request->ip()
            ]);

            DB::commit();

            // Auto-login the landlord
            auth()->login($landlord);

            return redirect()->route('landlord.dashboard')
                ->with('success', 'Registration completed successfully! Welcome to your landlord portal.');

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Error processing landlord invitation acceptance: ' . $e->getMessage(), [
                'invitation_id' => $invitation->id ?? 'unknown',
                'token' => $token,
                'landlord_id' => $invitation->landlord_id ?? 'unknown'
            ]);

            return redirect()->back()
                ->with('error', 'Failed to complete registration. Please try again.')
                ->withInput()
                ->with('token', $token);
        }
    }

    /**
     * ✅ NEW: Get invitation details for a property
     * Used in property show page to display invitation status
     */
    public function getPropertyInvitations($propertyId)
    {
        try {
            $invitations = LandlordInvitation::with(['landlord', 'inviter'])
                ->where('property_id', $propertyId)
                ->orderBy('created_at', 'desc')
                ->get();

            return response()->json([
                'success' => true,
                'invitations' => $invitations,
                'message' => 'Property invitations retrieved successfully'
            ]);

        } catch (\Exception $e) {
            Log::error('Failed to get property invitations: ' . $e->getMessage());

            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve property invitations',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * ✅ NEW: Get landlord's active invitations
     * Used when landlord logs in to show pending invitations
     */
    public function getLandlordActiveInvitations($landlordId)
    {
        try {
            $invitations = LandlordInvitation::with(['property', 'property.registrationPlan'])
                ->where('landlord_id', $landlordId)
                ->whereIn('status', [LandlordInvitation::STATUS_PENDING, LandlordInvitation::STATUS_SENT])
                ->where('expires_at', '>', now())
                ->orderBy('created_at', 'desc')
                ->get();

            return response()->json([
                'success' => true,
                'invitations' => $invitations,
                'message' => 'Active landlord invitations retrieved successfully'
            ]);

        } catch (\Exception $e) {
            Log::error('Failed to get landlord active invitations: ' . $e->getMessage());

            return response()->json([
                'success' => false,
                'message' => 'Failed to retrieve active invitations',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * ✅ UPDATED: Send invitation via multiple channels with token support
     */
    private function sendInvitation(LandlordInvitation $invitation): array
    {
        try {
            $landlord = $invitation->landlord;
            $property = $invitation->property;

            $availableChannels = $this->multiChannelInvitationService->getAvailableChannels($landlord);
            $channelsToUse = array_intersect($invitation->channels, $availableChannels);

            if (empty($channelsToUse)) {
                $invitation->markAsFailed('No available communication channels for this landlord.');
                return [
                    'success' => false,
                    'message' => 'No available communication channels for this landlord.'
                ];
            }

            $results = [];
            $successCount = 0;

            foreach ($channelsToUse as $channel) {
                $result = $this->multiChannelInvitationService->sendMessage(
                    $landlord,
                    $this->generateInvitationMessage($invitation),
                    'landlord_invitation',
                    [
                        'channel' => $channel,
                        'invitation_id' => $invitation->id,
                        'property_id' => $property->id,
                        'landlord_id' => $landlord->id,
                        'invitation_url' => $invitation->getInvitationUrl(),
                        'invitation_token' => $invitation->token,
                        'landlord' => $landlord,
                        'property' => $property,
                        'invitation' => $invitation
                    ]
                );

                $results[$channel] = $result;
                if ($result['success']) {
                    $successCount++;
                }
            }

            if ($successCount > 0) {
                $invitation->markAsSent($channelsToUse);
                
                Log::info('Landlord invitation sent successfully', [
                    'invitation_id' => $invitation->id,
                    'landlord_id' => $landlord->id,
                    'property_id' => $property->id,
                    'token' => $invitation->token,
                    'channels_successful' => array_keys(array_filter($results, fn($r) => $r['success'])),
                    'success_count' => $successCount
                ]);

                return [
                    'success' => true,
                    'message' => "Invitation sent via {$successCount} channel(s)",
                    'results' => $results,
                    'channels_successful' => array_keys(array_filter($results, fn($r) => $r['success'])),
                    'channels_attempted' => $channelsToUse,
                    'invitation_url' => $invitation->getInvitationUrl(),
                    'token' => $invitation->token
                ];
            } else {
                $invitation->markAsFailed('All communication channels failed');
                
                return [
                    'success' => false,
                    'message' => 'Failed to send invitation via any channel',
                    'results' => $results,
                    'channels_attempted' => $channelsToUse
                ];
            }

        } catch (\Exception $e) {
            Log::error('Failed to send landlord invitation: ' . $e->getMessage(), [
                'invitation_id' => $invitation->id,
                'token' => $invitation->token
            ]);
            $invitation->markAsFailed($e->getMessage());

            return [
                'success' => false,
                'message' => 'Failed to send invitation: ' . $e->getMessage()
            ];
        }
    }

    /**
     * Generate invitation message
     */
    private function generateInvitationMessage(LandlordInvitation $invitation): string
    {
        $landlord = $invitation->landlord;
        $property = $invitation->property;

        $message = "Hello {$landlord->name}!\n\n";

        switch ($invitation->invitation_type) {
            case LandlordInvitation::TYPE_PROPERTY_ADDED:
                $message .= "A new property has been added to your account:\n";
                break;
            case LandlordInvitation::TYPE_WELCOME:
                $message .= "Welcome to our property management system!\n";
                break;
            default: // registration
                $message .= "Your property has been registered in our system:\n";
        }

        $message .= "🏠 Property: {$property->property_name}\n";
        $message .= "📍 Location: {$property->street_name}, {$property->zone}\n";
        $message .= "🔢 Registration: {$property->registration_pattern}\n\n";

        if ($invitation->custom_message) {
            $message .= "{$invitation->custom_message}\n\n";
        }

        $message .= "To complete your registration and access your portal, please click:\n";
        $message .= "{$invitation->getInvitationUrl()}\n\n";
        $message .= "This link expires on {$invitation->expires_at->format('M j, Y')}";

        return $message;
    }

    /**
     * ✅ UPDATED: Get invitation statistics with token insights
     */
    public function statistics()
    {
        $stats = [
            'total_invitations' => LandlordInvitation::count(),
            'pending_invitations' => LandlordInvitation::pending()->count(),
            'active_invitations' => LandlordInvitation::active()->count(),
            'accepted_invitations' => LandlordInvitation::where('status', LandlordInvitation::STATUS_ACCEPTED)->count(),
            'expired_invitations' => LandlordInvitation::expired()->count(),
            'failed_invitations' => LandlordInvitation::where('status', LandlordInvitation::STATUS_FAILED)->count(),
            
            'invitations_by_type' => LandlordInvitation::groupBy('invitation_type')
                ->select('invitation_type', DB::raw('count(*) as count'))
                ->get()
                ->pluck('count', 'invitation_type'),
                
            'average_acceptance_time' => LandlordInvitation::where('status', LandlordInvitation::STATUS_ACCEPTED)
                ->whereNotNull('sent_at')
                ->whereNotNull('accepted_at')
                ->select(DB::raw('AVG(TIMESTAMPDIFF(HOUR, sent_at, accepted_at)) as avg_hours'))
                ->value('avg_hours'),
                
            // ✅ ADDED: Token-related statistics
            'invitations_with_tokens' => LandlordInvitation::whereNotNull('token')->count(),
            'unique_tokens' => LandlordInvitation::select('token')->distinct()->count(),
        ];

        return response()->json([
            'success' => true,
            'stats' => $stats,
            'message' => 'Invitation statistics retrieved successfully'
        ]);
    }

    /**
     * ✅ NEW: Regenerate token for an invitation
     */
    public function regenerateToken(LandlordInvitation $landlordInvitation)
    {
        DB::beginTransaction();

        try {
            $oldToken = $landlordInvitation->token;
            $newToken = LandlordInvitation::generateToken();
            
            $landlordInvitation->update([
                'token' => $newToken,
                'status' => LandlordInvitation::STATUS_PENDING,
                'sent_at' => null,
                'attempts' => 0
            ]);

            Log::info('Landlord invitation token regenerated', [
                'invitation_id' => $landlordInvitation->id,
                'old_token' => $oldToken,
                'new_token' => $newToken,
                'regenerated_by' => auth()->id()
            ]);

            DB::commit();

            return response()->json([
                'success' => true,
                'message' => 'Token regenerated successfully. The old invitation link is now invalid.',
                'new_invitation_url' => $landlordInvitation->getInvitationUrl(),
                'new_token' => $newToken
            ]);

        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Failed to regenerate token: ' . $e->getMessage(), [
                'invitation_id' => $landlordInvitation->id
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Failed to regenerate token. Please try again.',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}